version: '3'

services:
  mariadb_prueba:
    image: mariadb:latest
    container_name: mariadb_prueba
    environment:
      - MARIADB_USER=crud
      - MARIADB_PASSWORD=crud
      - MARIADB_DATABASE=crud
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb_data_prueba:/var/lib/mysql

  web_prueba:
    image: pepepfoter15/prueba:v1
    container_name: web_prueba
    environment:
      - DB_NAME=crud
      - DB_HOST=mariadb_prueba
      - DB_USER=crud
      - DB_PASSWORD=crud
    ports:
      - "8083:80"
    volumes:
      - web_logs_prueba:/var/log/web

volumes:
  mariadb_data_prueba:
    driver: local
  web_logs_prueba:
