version: '3'

services:
  prueba_mariadb:
    image: mariadb:latest
    container_name: prueba_mariadb
    environment:
      - MARIADB_USER=crud
      - MARIADB_PASSWORD=crud
      - MARIADB_DATABASE=crud
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb_data_prueba:/var/lib/mysql

  prueba_web:
    image: pepepfoter15/prueba:v1
    container_name: prueba_web
    environment:
      - DB_NAME=crud
      - DB_HOST=prueba_mariadb
      - DB_USER=crud
      - DB_PASSWORD=crud
    ports:
      - "8083:80"
    volumes:
      - web_logs_prueba:/var/log/web

volumes:
  mariadb_data_prueba:
    driver: local
  web_logs_prueba:
